### ISSUE TITLE
"Found multiple arguments for option ['height'], but you asked for only one"

### ISSUE THREAD

**Issue by nSadd** [GameParrot/lunarcmd#2]
**Describe the bug**
attempting to start the game with both the --width and --height args will result in it failing to start.
(1 at a time still works as intended)

**To Reproduce**
1. run "lunarcmd --width x --height y --version z"
2. game will not start, stating that multiple arguments were found for height

**Expected behavior**
successfully start the game with width x height y

**Screenshots**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/53909427/227094480-4f57ed73-ef4d-42ac-98c1-a9d180f53e31.png">

arg descriptions both say window width for some reason. I assume this has something to do with it
<img width="414" alt="image" src="https://user-images.githubusercontent.com/53909427/227094415-aa40ce62-4f0a-4ac1-be04-b06470df943a.png">

**Desktop:**
 - OS: macOS
 - OS Version 13.2.1

**Comment by GameParrot** [comment]
Fixed in 3.3
